import glob
import json
import os

app_json_paths = glob.glob("apps/**/*.json", recursive=True)

app_index = {}

keys_to_drop = [
    "links",
    "list_image",
    "screenshot_images",
    "header_images",
    "icon_image",
]

for app_json_path in app_json_paths:
    with open(app_json_path, "r") as f:
        app_json = json.load(f)

    base_dir = os.path.dirname(app_json_path)

    # Extract images
    images = {}
    if app_json.get("header_images"):
        images["header"] = f'{base_dir}/{app_json["id"]}-header.png'
    if app_json.get("icon_image"):
        images["icon"] = f'{base_dir}/{app_json["id"]}-icon.png'
    if app_json.get("list_image"):
        images["list"] = f'{base_dir}/{app_json["id"]}-list.png'
    if screenshot_images := app_json.get("screenshot_images"):
        for i in range(len(screenshot_images)):
            images["screenshots"] = f'{base_dir}/{app_json["id"]}-screen-{i}.png'
    app_json["images"] = images

    app_json["tags"] = []

    # Add a tag for auto-generated apps
    if app_json.get("uuid", "").startswith("13371337-"):
        app_json["tags"].append("autogenerated")

    # Fix app URL (only relevant for non-companion-apps)
    if "latest_release" in app_json:
        pbw_path = f"{base_dir}/{app_json['id']}.pbw"
        # If the app is missing the pbw, then don't tag it accordingly
        if not os.path.exists(pbw_path):
            app_json["tags"].append("missing-pbw")
            del app_json["latest_release"]["pbw_file"]
        else:
            app_json["latest_release"]["pbw_file"] = pbw_path

    # Clean up keys
    for key in keys_to_drop:
        if key in app_json:
            del app_json[key]

    app_index[app_json["id"]] = app_json

with open("app_index.json", "w") as f:
    json.dump(app_index, f, indent=4)
